# Generated by Django 4.0.6 on 2022-11-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
