# Generated by Django 4.0.6 on 2022-11-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='bottom_gradient_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='top_gradient_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
