# Generated by Django 4.0.6 on 2022-12-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='english_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Intermediate'), (1, 'Upper Intermediate'), (2, 'Advanced')], default=1),
            preserve_default=False,
        ),
    ]
