# Generated by Django 4.0.6 on 2022-11-11 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_style_bottom_gradient_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersentence',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Random generated'), (1, 'Saved from library'), (2, 'Created by user')]),
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sentence', models.CharField(max_length=20)),
                ('meaning', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Normal'), (1, 'Group')])),
                ('source_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Short video'), (1, 'Info card')], null=True)),
                ('info_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.infocard')),
                ('short_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shortvideo')),
            ],
            options={
                'db_table': 'sentences',
            },
        ),
    ]
