# Generated by Django 4.0.6 on 2022-11-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usersentence_origin_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='extras',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usersentence',
            name='extras',
            field=models.TextField(blank=True, default=''),
        ),
    ]
