const questions = [
    "What did you eat today? Can you describe it?",
    "Have you ever had to eat in a hurry? How was it!?",
    "When a friend come over, do you like to cook for fun? Hm Like what?",
    "What food would you love to eat today? Explain me :P",
    "Which food do you like the most?",
    "What delicious and truly perfect foods you have learned to cook?",
    "Do you like pork ribs? When do you eat them? With Coke, juice, Fanta maybe?",
    "Have you ordered food online recently? How was it?",
    "Did you eat at home today or at work, college or in what place?",
    "Who will you have lunch with today?",
    "Do your pets eat food at the same time as you?",
    "Do you drink Coke, plain water, coffee or a soft drink at lunchtime? I'm hearinG! :D",
    "What did you eat for breakfast today? At what time, with who? Describe it to me :D",
    "What did you eat for dinner today or what would be good for? Hmm",
    "Hmm, is cooking difficult? Or do you usually cook damn delicious meals at home?",
    "Have you tried to cook something that you have seen on Youtube?",
    "What is your favorite restaurant? What makes it special? 🍖😊",
    "What is your favorite vegan food? 🥗🍅😄",
    "Can you summarize your day?",
    "Hey, Too cold today?",
    "Tell me three good things about today. 🙊👌",
    "Did you hang out with someone? 🍺",
    "Did you study today? What especially?",
    "What did you have to do today?",
    "Did you have to cook today? 🍖😏",
    "Do you check your social networks when you wake up?",
    "Hmm... What did you have to do at work?",
    "How is your productive morning routine in quarantine?",
    "What were you in today's morning?",
    "Do you study at night? How is your late night study session?",
    "Do you do home workout? What is your everyday workout routine?",
    "How many cups of coffee did you have today!? ☕",
    "How would you like today to end?",
    "What will you do tomorrow? Are you going to be busy? On what?",
    "Something you gonna do now at night? Do you have something in mind?",
    "As we all have believed that there will be a judgment day, it happened. A huge meteor fell on earth turning every human into transformers (Yes, autobots and decepticons like the movie Transformers) Depending on your personal traits and character, what vehicle would you be?",
    "The zombie virus has broken out. It has infected over half of the population of the world. You were also unfortunately infected and have turned into a zombie. Your friends who you have travelled with are hesitating to kill you. Would you eat your best friend?",
    "What if in the year 2045 you are powerful enough to start your own society. What kind of society would you establish? What would be the goal of your established society?",
    "If you had the fascinating ability to live in any one's head (read their minds and know what they are thinking) for one whole hour. Whose head would you get in? Any particular reason?",
    "So you got yourself a pet puppy from a local pet shop. You had fun with playing with him during day but never lets you sleep during the night because it keeps crying out. What do you do?",
    "While walking down the subway late at night, a group of thugs point a knife at you and are about to kill you. However to show some mercy they allow you to make one phone call to just one person for 1 minute. Who would you call?",
    "Let's say you walk into the kitchen and drink a pink drink thinking its juice but suddenly you become invisible after drinking.  What would you do first?",
    "So there's this app and it's called the teleporter. Doesn't take up too much space on your phone so you download it. The description given is : “Think and concentrate on where you want to go then press the red button”. In a seconds time you are at Hawaii. Where do you go next?",
    "A pink bunny is in your yard. It's very cute and fluffy. But... a bird flies over its head. The bunny leaps into the air and swallows the bird in one gulp. It turns to face the house. What do you do?",
    "How do you think the world will end?",
    "What is the biggest priority in your life right now?",



]